### ISSUE TITLE
[Enhancement] Popup should animate into view

### ISSUE THREAD

**Issue by Illedan** [DIPSAS/DIPS.Xamarin.UI#73]
## Summary
Popup does now simply "pop up", but it would be more smooth if it slides to open / close.

## API Changes

Add `SlideDirection` to popup.

Options should be `Up`, `Down` or `None`.
These directions will be used in reverse when closing the popup.

**Comment by haavamoa** [comment]
I would concider adding a `Animation` property instead. This is due to the fact that other animations can be preffered in the future.

Maybe we can try to use the enum flags approach:

`Animation = Slide, Up`
`Animation = Slide, Down`
`Animation = None` (default)

Future cases:
`Animation = FadeIn, Up`
`Animation = FadeIn, Down`

**Comment by Illedan** [comment]
Should this Animation flag be a shared flag between multiple components?

**Comment by haavamoa** [comment]
> Should this Animation flag be a shared flag between multiple components?

Nah, I think it should be specific to this component as the animations in this enum might not fit for other components (and visa virsa) .

**Comment by haavamoa** [comment]
Direction of the animation should be something that the component knows, and not something the consumer should have to set. So we should end up with a clean enum without flags:

```
Animation = "Slide" 
Animation = "Fade" 
Animation = "None" (default)
```
